import Link from 'next/link';
import { ArrowRight, Check, Globe2, Sparkles } from 'lucide-react';
import { getSupabaseAdmin } from '@/server/supabase-admin';
import { PlanComparison } from '@/components/plan-comparison';
import { MarketingFAQ, MarketingTestimonials, Reveal } from '@/components/marketing-content';

export const dynamic = 'force-dynamic';

const countries = [
  { code: 'IN', name: 'India' }, { code: 'US', name: 'United States' }, { code: 'BD', name: 'Bangladesh' }, { code: 'GB', name: 'United Kingdom' }, { code: 'AE', name: 'United Arab Emirates' },
];

const comparisonRows = [
  ['Free', '10 monthly credits', '1 upload / project', 'Watermark', 'Basic image analysis'],
  ['Pro', '100 monthly credits', '10 uploads / project', 'No watermark', 'All image analysis levels'],
  ['Business', '1000 monthly credits', '30 uploads / project', 'No watermark', 'All image analysis levels + higher volume'],
];

export default async function PricingPage() {
  const admin = getSupabaseAdmin();
  const { data: prices } = await admin.from('plan_prices').select('plan_id,country_code,currency,unit_amount_minor').eq('active', true).in('country_code', countries.map((country) => country.code));
  const defaultPrices = Object.fromEntries((prices ?? []).filter((price) => price.country_code === 'IN').map((price) => [price.plan_id, price.unit_amount_minor]));
  const currency = (prices?.find((price) => price.country_code === 'IN')?.currency ?? 'USD').toUpperCase();

  return <main className="min-h-screen overflow-x-hidden bg-[#fbfbfa] text-slate-950">
    <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-slate-950 text-white"><Sparkles className="size-4" /></span><span><span className="block text-sm font-semibold">Solamentis</span><span className="block text-xs text-slate-500">Creative Intelligence</span></span></Link><div className="flex items-center gap-1"><a href="#compare" className="hidden rounded-xl px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100 sm:inline-flex">Compare</a><a href="#faq" className="hidden rounded-xl px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-100 sm:inline-flex">FAQ</a><Link href="/login" className="inline-flex min-h-10 items-center rounded-xl px-3 text-sm font-semibold text-slate-600 hover:bg-slate-100">Sign in</Link></div></div></header>

    <section className="relative mx-auto grid max-w-7xl gap-10 px-4 pb-16 pt-14 sm:px-6 sm:pt-20 lg:grid-cols-[1fr_.8fr] lg:px-8 lg:pb-24"><Reveal><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-400">Plans & pricing</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Pay for the creative work you actually run.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">Pick a monthly capacity, understand exactly what costs credits, and scale from experimentation to recurring production without changing the creative workspace.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 text-sm font-semibold text-white">Start with free <ArrowRight className="size-4" /></Link><a href="#compare" className="inline-flex min-h-12 items-center justify-center rounded-2xl border border-slate-200 bg-white px-5 text-sm font-semibold text-slate-700">See full comparison</a></div></Reveal><Reveal delay={120}><div className="relative overflow-hidden rounded-[32px] border border-slate-200 bg-slate-950 p-2 shadow-2xl"><div className="hero-orbit"><div className="hero-orbit__glow"/><div className="hero-orbit__ring hero-orbit__ring--one"/><div className="hero-orbit__ring hero-orbit__ring--two"/><div className="hero-orbit__core"><span>PLANS</span></div><div className="hero-orbit__node hero-orbit__node--one"/><div className="hero-orbit__node hero-orbit__node--two"/><div className="hero-orbit__node hero-orbit__node--three"/></div><div className="relative flex min-h-[330px] items-end rounded-[26px] bg-slate-900 p-5"><div className="w-full rounded-2xl border border-white/10 bg-black/25 p-4 backdrop-blur-xl"><p className="text-[11px] uppercase tracking-[.18em] text-slate-500">Simple mental model</p><div className="mt-2 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-white/5 p-3 text-slate-300">Capacity</div><div className="rounded-xl bg-white/5 p-3 text-slate-300">Credits</div><div className="rounded-xl bg-white/5 p-3 text-slate-300">Operations</div></div></div></div></div></Reveal></section>

    <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-px sm:grid-cols-3"><div className="p-6 sm:p-8"><p className="text-2xl font-semibold">1 month</p><p className="mt-1 text-sm text-slate-500">Flexible billing period.</p></div><div className="border-slate-200 p-6 sm:border-x sm:p-8"><p className="text-2xl font-semibold">6 months</p><p className="mt-1 text-sm text-slate-500">Longer commitment and eligible feature access.</p></div><div className="p-6 sm:p-8"><p className="text-2xl font-semibold">1 year</p><p className="mt-1 text-sm text-slate-500">Highest long-period commitment option.</p></div></div></section>

    <section id="compare" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><Reveal><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-400">Choose your plan</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">Compare plans before you pay.</h2><p className="mt-4 text-sm leading-6 text-slate-500">Regional prices come from your billing country. The interactive selector below keeps the existing checkout/pricing logic while making the differences easier to scan.</p></div></Reveal><div className="mt-8"><PlanComparison prices={defaultPrices} currency={currency} initialPlan="pro" /></div></section>

    <section className="border-y border-slate-200 bg-slate-50/70"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><Reveal><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white shadow-sm"><Globe2 className="size-5 text-slate-700" /></span><div><h2 className="text-base font-semibold">Regional pricing</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-500">Prices are selected by billing country at checkout. This view currently defaults to India when an authenticated billing country is not available.</p></div></div></Reveal></div></section>

    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><Reveal><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-slate-400">At a glance</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">What changes as you scale?</h2></div></Reveal><div className="mt-8 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-slate-200 bg-slate-50"><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[.12em] text-slate-400">Plan</th><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[.12em] text-slate-400">Credits</th><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[.12em] text-slate-400">Project uploads</th><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[.12em] text-slate-400">Image output</th><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[.12em] text-slate-400">Analysis</th></tr></thead><tbody>{comparisonRows.map((row) => <tr key={row[0]} className="border-b border-slate-100 last:border-0">{row.map((cell, index) => <td key={`${row[0]}-${index}`} className={`px-5 py-4 text-sm ${index === 0 ? 'font-semibold text-slate-900' : 'text-slate-500'}`}>{index === 4 ? <span className="inline-flex items-center gap-2"><Check className="size-4 text-emerald-600" />{cell}</span> : cell}</td>)}</tr>)}</tbody></table></div></div></section>

    <MarketingTestimonials />
    <div id="faq"><MarketingFAQ /></div>

    <section className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><Reveal><div className="rounded-[32px] bg-slate-950 p-7 text-white shadow-2xl sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Need a decision rule?</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">Start Free for a workflow test. Choose Pro for repeat work. Choose Business for volume.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-400">The plan is not a lock-in to a different product. You are choosing capacity and access to more expensive operations.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white px-5 text-sm font-semibold text-slate-950">Create account <ArrowRight className="size-4" /></Link><Link href="/" className="inline-flex min-h-12 items-center justify-center rounded-2xl border border-white/15 px-5 text-sm font-semibold text-white">Back to home</Link></div></div></Reveal></section>

    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 md:grid-cols-[1.5fr_1fr_1fr_1fr] lg:px-8"><div><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-slate-950 text-white"><Sparkles className="size-4"/></span><span className="text-sm font-semibold">Solamentis</span></div><p className="mt-4 max-w-sm text-sm leading-6 text-slate-500">AI creative infrastructure for generation, analysis, video ads, projects, history and private media delivery.</p></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Explore</p><div className="mt-4 space-y-3 text-sm"><Link href="/" className="block text-slate-600 hover:text-slate-950">Home</Link><Link href="/dashboard/media" className="block text-slate-600 hover:text-slate-950">Media Studio</Link><Link href="/dashboard/projects" className="block text-slate-600 hover:text-slate-950">Projects</Link></div></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Account</p><div className="mt-4 space-y-3 text-sm"><Link href="/signup" className="block text-slate-600 hover:text-slate-950">Start free</Link><Link href="/login" className="block text-slate-600 hover:text-slate-950">Sign in</Link><Link href="/pricing" className="block text-slate-600 hover:text-slate-950">Pricing</Link></div></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Legal</p><div className="mt-4 space-y-3 text-sm"><Link href="/terms" className="block text-slate-600 hover:text-slate-950">Terms</Link><a href="#faq" className="block text-slate-600 hover:text-slate-950">FAQ</a></div></div></div><div className="mx-auto flex max-w-7xl flex-col gap-2 border-t border-slate-200 px-4 py-6 text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>© {new Date().getFullYear()} Solamentis.</span><span>Regional pricing · credit-based usage · private media</span></div></footer>
  </main>;
}
