import Link from 'next/link';
import { ArrowRight, Check, CreditCard, FileImage, Gauge, Layers3, LockKeyhole, ScanSearch, ShieldCheck, Sparkles, UploadCloud, WandSparkles, Zap } from 'lucide-react';
import { MarketingCTA, MarketingExamples, MarketingFAQ, MarketingHero3D, MarketingProof, MarketingTestimonials, MarketingWorkflow, Reveal } from '@/components/marketing-content';

const workflow = [
  { number: '01', icon: UploadCloud, title: 'Bring a reference', body: 'Upload a visual when you need product context, composition, or a starting point. New reference uploads are compressed before storage.' },
  { number: '02', icon: WandSparkles, title: 'Describe the outcome', body: 'Write the creative goal, choose a destination and quality, and let the configured provider handle the AI operation.' },
  { number: '03', icon: ScanSearch, title: 'Create, analyze, refine', body: 'Generate images, inspect image signals, create short-form video ads, or refine an existing result in one workspace.' },
  { number: '04', icon: FileImage, title: 'Keep the useful version', body: 'History connects the job, output and metadata so you can reopen work instead of starting over.' },
];

const principles = [
  { icon: Layers3, title: 'One creative workspace', body: 'Generation, image analysis, editing, projects, history and delivery share one product model.' },
  { icon: Zap, title: 'Provider-flexible architecture', body: 'Provider and model routing is configuration-driven, so infrastructure can evolve without redesigning the creative UI.' },
  { icon: Gauge, title: 'Usage you can see', body: 'Credits are attached to the operation and quality tier so users can understand the cost before running work.' },
  { icon: LockKeyhole, title: 'Private by default', body: 'The application uses authenticated storage and signed asset delivery rather than a public media bucket.' },
];

export default function Home() {
  return <main className="min-h-screen overflow-x-hidden bg-[#fbfbfa] text-slate-950">
    <div className="pointer-events-none fixed inset-0 bg-grid opacity-50" />
    <nav className="sticky top-0 z-50 border-b border-slate-200/70 bg-white/80 backdrop-blur-xl">
      <div className="mx-auto flex min-h-20 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
        <Link href="/" className="flex items-center gap-3" aria-label="Solamentis home"><span className="grid size-10 place-items-center rounded-2xl bg-slate-950 text-white shadow-lg"><Sparkles className="size-5" /></span><span><span className="block text-sm font-semibold tracking-tight">Solamentis</span><span className="block text-xs text-slate-500">Creative Intelligence</span></span></Link>
        <div className="hidden items-center gap-1 md:flex"><a href="#how-it-works" className="rounded-xl px-3 py-2 text-sm font-medium text-slate-600 hover:bg-white">How it works</a><a href="#features" className="rounded-xl px-3 py-2 text-sm font-medium text-slate-600 hover:bg-white">Features</a><a href="#plans" className="rounded-xl px-3 py-2 text-sm font-medium text-slate-600 hover:bg-white">Plans</a></div>
        <div className="flex items-center gap-1 sm:gap-2"><Link href="/pricing" className="hidden min-h-10 items-center rounded-xl px-3 text-sm font-medium text-slate-600 hover:bg-slate-100 sm:inline-flex">Pricing</Link><Link href="/login" className="hidden min-h-10 items-center rounded-xl px-3 text-sm font-medium text-slate-600 hover:bg-white sm:inline-flex">Sign in</Link><Link href="/signup" className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-slate-950 px-3.5 text-sm font-semibold text-white shadow-lg hover:bg-slate-800">Start creating<ArrowRight className="size-4" /></Link></div>
      </div>
    </nav>

    <section className="relative mx-auto grid max-w-7xl gap-12 px-4 pb-20 pt-14 sm:px-6 sm:pt-20 lg:grid-cols-[1fr_.9fr] lg:px-8 lg:pb-28 lg:pt-24">
      <div className="self-center"><Reveal><div className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-600 shadow-sm"><span className="size-1.5 rounded-full bg-emerald-500" /> One workspace for AI creative work</div><h1 className="mt-6 max-w-3xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl lg:text-7xl">Create, analyze, refine, and ship visual work.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg sm:leading-8">Solamentis brings image generation, image intelligence, short-form video ads, projects, history, usage and private media delivery into one understandable SaaS workflow.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-slate-950 px-5 text-sm font-semibold text-white shadow-xl hover:bg-slate-800">Create your workspace<ArrowRight className="size-4" /></Link><Link href="/pricing" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><CreditCard className="size-4" /> See plans & credits</Link></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-xs font-medium text-slate-500"><span className="inline-flex items-center gap-2"><Check className="size-4 text-emerald-600" /> Private assets</span><span className="inline-flex items-center gap-2"><Check className="size-4 text-emerald-600" /> Usage-based credits</span><span className="inline-flex items-center gap-2"><Check className="size-4 text-emerald-600" /> Configurable providers</span></div></Reveal></div>
      <Reveal delay={120}><MarketingHero3D /></Reveal>
    </section>

    <section className="relative border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-px sm:grid-cols-3"><div className="p-6 sm:p-8"><p className="text-2xl font-semibold tracking-tight">Image + video + analysis</p><p className="mt-1 text-sm text-slate-500">Multiple creative operations in one studio.</p></div><div className="border-slate-200 p-6 sm:border-x sm:p-8"><p className="text-2xl font-semibold tracking-tight">Private media</p><p className="mt-1 text-sm text-slate-500">Authenticated access and signed delivery.</p></div><div className="p-6 sm:p-8"><p className="text-2xl font-semibold tracking-tight">One history</p><p className="mt-1 text-sm text-slate-500">Jobs, outputs and metadata stay connected.</p></div></div></section>

    <section id="how-it-works" className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><Reveal><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">How it works</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">A simple A-to-Z creative loop.</h2><p className="mt-4 text-base leading-7 text-slate-600">Start with a brief, move through the operation you need, inspect the result, then keep the useful version. The UI stays focused while the platform handles the infrastructure.</p></div></Reveal><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{workflow.map(({ number, icon: Icon, title, body }, index) => <Reveal key={number} delay={index * 70}><article className="h-full rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition duration-500 hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><span className="text-xs font-semibold tracking-[0.15em] text-slate-300">{number}</span><span className="grid size-10 place-items-center rounded-xl bg-slate-100"><Icon className="size-5" /></span></div><h3 className="mt-7 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p></article></Reveal>)}</div></section>

    <MarketingExamples />

    <section id="features" className="relative border-y border-slate-200 bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-24"><Reveal><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Product architecture</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">Not just AI buttons. A system around them.</h2><p className="mt-4 text-base leading-7 text-slate-400">Solamentis connects the creative operation with storage, provider routing, usage, safety and history so the product behaves like software—not a collection of disconnected experiments.</p></div></Reveal><div className="mt-10 grid gap-4 md:grid-cols-2">{principles.map(({ icon: Icon, title, body }, index) => <Reveal key={title} delay={index * 70}><article className="rounded-3xl border border-white/10 bg-white/5 p-6 transition duration-500 hover:bg-white/[.07]"><span className="grid size-10 place-items-center rounded-xl bg-white/10"><Icon className="size-5" /></span><h3 className="mt-5 text-base font-semibold">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-slate-400">{body}</p></article></Reveal>)}</div></div></section>

    <MarketingWorkflow />
    <MarketingProof />
    <MarketingTestimonials />

    <section id="plans" className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-24"><Reveal><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400">Plans & usage</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-5xl">A plan for a test, a team, or a production workflow.</h2><p className="mt-4 text-base leading-7 text-slate-600">Free starts at 10 monthly credits, Pro at 100, and Business at 1000. Operation quality determines credit usage.</p></div><Link href="/pricing" className="inline-flex min-h-11 shrink-0 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-semibold text-white">Compare every plan<ArrowRight className="size-4" /></Link></div></Reveal><div className="mt-10 grid gap-4 lg:grid-cols-3">{[['Free','10','1 project upload','Best for trying the workflow'],['Pro','100','10 project uploads','For recurring creative work'],['Business','1000','30 project uploads','For higher-volume teams']].map(([name, credits, uploads, fit]) => <Reveal key={name}><article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-semibold">{name}</p><p className="mt-4 text-4xl font-semibold tracking-tight">{credits}<span className="ml-1 text-sm font-medium text-slate-400">credits / month</span></p><p className="mt-4 text-sm text-slate-600">{uploads}</p><p className="mt-2 text-xs text-slate-400">{fit}</p></article></Reveal>)}</div></section>

    <div id="faq"><MarketingFAQ /></div>
    <MarketingCTA />

    <footer className="border-t border-slate-200 bg-slate-50"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 md:grid-cols-[1.5fr_1fr_1fr_1fr] lg:px-8"><div><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-slate-950 text-white"><Sparkles className="size-4" /></span><span className="text-sm font-semibold">Solamentis</span></div><p className="mt-4 max-w-sm text-sm leading-6 text-slate-500">A creative intelligence workspace for generation, analysis, video ads, projects, history and private media delivery.</p></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Product</p><div className="mt-4 space-y-3 text-sm"><Link href="/dashboard/media" className="block text-slate-600 hover:text-slate-950">Media Studio</Link><Link href="/dashboard/projects" className="block text-slate-600 hover:text-slate-950">Projects</Link><Link href="/dashboard/history" className="block text-slate-600 hover:text-slate-950">History</Link></div></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Plans</p><div className="mt-4 space-y-3 text-sm"><Link href="/pricing" className="block text-slate-600 hover:text-slate-950">Pricing</Link><Link href="/signup" className="block text-slate-600 hover:text-slate-950">Start free</Link><Link href="/login" className="block text-slate-600 hover:text-slate-950">Sign in</Link></div></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Company</p><div className="mt-4 space-y-3 text-sm"><a href="#faq" className="block text-slate-600 hover:text-slate-950">FAQ</a><Link href="/terms" className="block text-slate-600 hover:text-slate-950">Terms</Link></div></div></div><div className="mx-auto flex max-w-7xl flex-col gap-2 border-t border-slate-200 px-4 py-6 text-xs text-slate-400 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>© {new Date().getFullYear()} Solamentis.</span><span>Creative intelligence · private media · configurable AI infrastructure</span></div></footer>
  </main>;
}
