'use client';

import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock3, Save, ShieldCheck, Sparkles, UserRound, Palette, LockKeyhole } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardBody, CardHeader } from '@/components/ui/card';
import { PageLoader } from '@/components/ui/page-loader';
import { DISPLAY_PLANS, type PlanId } from '@/config/plan-display';
import { PlanComparison } from '@/components/plan-comparison';
import { BillingHistory, type BillingTransaction } from '@/components/billing-history';
import { canUseWorkspaceTheme, useWorkspaceTheme } from '@/components/workspace-theme';

const countries=[['IN','India'],['US','United States'],['BD','Bangladesh'],['GB','United Kingdom'],['AE','United Arab Emirates']];
type Profile={full_name:string|null;email:string|null;phone:string|null;country_code:string|null;country_name:string|null;locale:string|null;plan_id:PlanId|null;created_at:string;updated_at:string;last_seen_at:string|null;last_login_at:string|null;login_count:number};
type Subscription={id:string;plan_id:PlanId;status:string;provider:string|null;current_period_start:string|null;current_period_end:string|null;country_code:string|null;currency:string|null;cancel_at_period_end:boolean;created_at:string;updated_at:string};
type ApiPayload={profile:Profile;subscription:Subscription|null;planPrice:{currency:string;unit_amount_minor:number};planPrices:Record<string,number>;transactions:BillingTransaction[]};

export default function SettingsPage(){
 const [payload,setPayload]=useState<ApiPayload|null>(null); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [country,setCountry]=useState('IN'); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [compare,setCompare]=useState(false);
 const { theme, setTheme, themes } = useWorkspaceTheme();
 useEffect(()=>{fetch('/api/profile',{cache:'no-store'}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to load profile.');setPayload(data);setName(data.profile?.full_name||'');setPhone(data.profile?.phone||'');setCountry(data.profile?.country_code||'IN');}).catch(error=>setMessage(error instanceof Error?error.message:'Unable to load profile.')).finally(()=>setLoading(false));},[]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');try{const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({full_name:name.trim(),phone:phone.trim(),country_code:country})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to save profile.');setPayload(data);setMessage('Profile saved successfully.');}catch(error){setMessage(error instanceof Error?error.message:'Network error. Please try again.');}finally{setSaving(false);}}
 const plan=useMemo(()=>DISPLAY_PLANS.find(item=>item.id===(payload?.profile?.plan_id||'free'))||DISPLAY_PLANS[0],[payload]); const currency=payload?.planPrice.currency||'USD'; const monthly=payload?.planPrice.unit_amount_minor??plan.monthlyFallbackMinor; const sub=payload?.subscription; const PlanIcon=plan.icon;
 if(loading)return <PageLoader label="Loading settings…"/>;
 return <div className="space-y-7 sm:space-y-8">
   <div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--workspace-muted)]">Settings</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-4xl">Workspace control center</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--workspace-muted)]">Profile, plan, appearance, and verified payment history — with the same visual system used across your workspace.</p></div>
   <section className="rounded-3xl border border-[var(--workspace-border)] bg-[var(--workspace-panel)] p-5 shadow-sm sm:p-6"><div className="flex items-start gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[var(--workspace-soft)]"><Palette className="size-5"/></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--workspace-muted)]">Workspace appearance</p><h2 className="mt-1 text-lg font-semibold">Choose your studio atmosphere</h2><p className="mt-1 text-sm text-[var(--workspace-muted)]">Three themes are free. Pro unlocks two more, and Business unlocks the final two premium themes.</p></div></div>
     <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{themes.map((item)=>{const selected=theme===item.id;const allowed=canUseWorkspaceTheme(item.id,plan.id);return <button key={item.id} type="button" onClick={()=>allowed&&setTheme(item.id)} disabled={!allowed} aria-pressed={selected} aria-disabled={!allowed} className={`group rounded-2xl border p-4 text-left transition ${selected?'border-[var(--workspace-accent)] ring-2 ring-[var(--workspace-accent)]/15':'border-[var(--workspace-border)]'} ${allowed?'hover:border-[var(--workspace-accent)]/50':'cursor-not-allowed opacity-55'}`}><div className="flex gap-1.5 rounded-xl p-2" style={{background:item.swatches[1]}}>{item.swatches.map((swatch)=><span key={swatch} className="h-8 flex-1 rounded-lg" style={{background:swatch}}/>)}</div><div className="mt-4 flex items-center justify-between gap-3"><span className="text-sm font-semibold">{item.name}</span>{selected?<span className="inline-flex items-center gap-1 rounded-full bg-[var(--workspace-fg)] px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-white"><CheckCircle2 className="size-3"/>Active</span>:!allowed?<span className="inline-flex items-center gap-1 rounded-full bg-[var(--workspace-soft)] px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-[var(--workspace-muted)]"><LockKeyhole className="size-3"/>{item.minPlan}</span>:null}</div><p className="mt-1 text-xs leading-5 text-[var(--workspace-muted)]">{item.description}</p></button>})}</div>
   </section>
   <section className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(300px,.9fr)]"><Card><CardHeader><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[var(--workspace-soft)]"><UserRound className="size-5"/></div><div><h2 className="text-sm font-semibold">Personal information</h2><p className="text-xs text-[var(--workspace-muted)]">Your email remains linked to your authenticated account.</p></div></div></CardHeader><CardBody><form onSubmit={save}><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Full name<input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-[var(--workspace-border)] bg-[var(--workspace-soft)] px-3.5 py-3 outline-none focus:border-[var(--workspace-accent)] focus:ring-4 focus:ring-[var(--workspace-accent)]/10"/></label><label className="text-sm font-medium">Email<input disabled value={payload?.profile?.email||''} className="mt-2 min-h-11 w-full rounded-xl border border-[var(--workspace-border)] bg-[var(--workspace-soft)] px-3.5 py-3 text-[var(--workspace-muted)]"/></label><label className="text-sm font-medium">Phone number<input autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91 …" className="mt-2 min-h-11 w-full rounded-xl border border-[var(--workspace-border)] bg-[var(--workspace-soft)] px-3.5 py-3 outline-none focus:border-[var(--workspace-accent)] focus:ring-4 focus:ring-[var(--workspace-accent)]/10"/></label><label className="text-sm font-medium sm:col-span-2">Country<select value={country} onChange={e=>setCountry(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-[var(--workspace-border)] bg-[var(--workspace-soft)] px-3.5 py-3 outline-none focus:border-[var(--workspace-accent)] focus:ring-4 focus:ring-[var(--workspace-accent)]/10">{countries.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select><span className="mt-2 block text-xs font-normal leading-5 text-[var(--workspace-muted)]">Used for regional pricing display and localization.</span></label></div>{message&&<p role="status" className={`mt-5 rounded-xl p-3 text-sm ${message.includes('success')?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{message.includes('success')&&<CheckCircle2 className="mr-2 inline size-4"/>}{message}</p>}<Button type="submit" loading={saving} className="mt-6">{saving?'Saving…':'Save profile'}{!saving&&<Save className="size-4"/>}</Button></form></CardBody></Card>
   <Card><CardBody><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--workspace-muted)]">Current plan</p><div className="mt-3 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[var(--workspace-fg)] text-white"><PlanIcon className="size-5"/></span><div><h2 className="text-xl font-semibold capitalize">{plan.name}</h2><p className="text-xs text-[var(--workspace-muted)]">{plan.description}</p></div></div></div>{plan.id==='pro'&&<span className="rounded-full bg-[var(--workspace-fg)] p-2 text-white shadow-lg" title="Premium"><Sparkles className="size-4"/></span>}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Detail label="Started" value={sub?.created_at?new Date(sub.created_at).toLocaleDateString():payload?.profile?.created_at?new Date(payload.profile.created_at).toLocaleDateString():'—'} icon={<CalendarDays className="size-4"/>}/><Detail label="Current cost" value={monthly?`${currency} ${(monthly/100).toLocaleString()} / month`:'Free'} /><Detail label="Current period end" value={sub?.current_period_end?new Date(sub.current_period_end).toLocaleDateString():'No expiry on Free'} icon={<Clock3 className="size-4"/>}/><Detail label="Status" value={sub?.status||'active'} icon={<ShieldCheck className="size-4"/>}/></div><div className="mt-6 space-y-2">{plan.features.map(feature=><div key={feature} className="flex items-center gap-2 text-sm text-[var(--workspace-fg)]"><CheckCircle2 className="size-4 text-emerald-600"/>{feature}</div>)}</div><div className="mt-6 flex flex-col gap-2 sm:flex-row"><Link href="/dashboard/billing" className="workspace-primary inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold">Manage plan</Link><button type="button" onClick={()=>setCompare(value=>!value)} className="inline-flex min-h-11 flex-1 items-center justify-center rounded-xl border border-[var(--workspace-border)] px-4 text-sm font-semibold text-[var(--workspace-muted)] hover:bg-[var(--workspace-hover)]">{compare?'Hide comparison':'Compare all plans'}</button></div></CardBody></Card></section>
   <BillingHistory transactions={payload?.transactions??[]} />
   {compare&&<section className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--workspace-muted)]">Plan comparison</p><h2 className="mt-2 text-xl font-semibold">Compare features and period pricing</h2></div><PlanComparison prices={payload?.planPrices??{}} currency={currency} initialPlan={plan.id}/></section>}
 </div>;
}
function Detail({icon,label,value}:{icon?:ReactNode;label:string;value:string}){return <div className="min-w-0 rounded-2xl border border-[var(--workspace-border)] bg-[var(--workspace-soft)] p-3.5"><div className="flex items-center gap-2 text-[11px] font-medium uppercase tracking-wide text-[var(--workspace-muted)]">{icon}{label}</div><p className="mt-1.5 break-words text-sm font-semibold">{value}</p></div>}
