import Link from 'next/link';
import { ArrowUpRight, FolderKanban, ImagePlus, Layers3, ScanSearch, ShieldCheck, Sparkles, Video } from 'lucide-react';
import { getSupabaseServerClient } from '@/server/supabase';
import { getSupabaseAdmin } from '@/server/supabase-admin';
import { Card, CardBody } from '@/components/ui/card';
import { RecentGenerations } from '@/components/recent-generations';
import { CreditWallet } from '@/components/credit-wallet';

export default async function DashboardPage() {
  const client = await getSupabaseServerClient(); const { data: { user } } = await client.auth.getUser(); if (!user) return null;
  const admin = getSupabaseAdmin();
  const [{ data: profile }, { data: projects }, { data: jobs }, { data: nextGrant }] = await Promise.all([
    admin.from('profiles').select('full_name,plan_id,credits,credits_reserved,monthly_credits,addon_credits,country_name,billing_country_code,country_code').eq('id', user.id).single(),
    admin.from('projects').select('id,name,platform,width,height,updated_at').eq('user_id', user.id).order('updated_at', { ascending: false }).limit(6),
    admin.from('generation_jobs').select('id,status,prompt,quality,created_at,completed_at,operation,provider,model').eq('user_id', user.id).order('created_at', { ascending: false }).limit(6),
    admin.from('credit_grants').select('remaining_amount,expires_at').eq('user_id', user.id).in('source', ['credit_product_purchase', 'addon_purchase']).gt('remaining_amount', 0).not('expires_at', 'is', null).order('expires_at', { ascending: true }).limit(1).maybeSingle(),
  ]);
  const country = String(profile?.billing_country_code || profile?.country_code || 'IN').toUpperCase();
  const [{ data: region }, { data: products }, { data: productPrices }] = await Promise.all([
    admin.from('pricing_regions').select('country_code,currency').eq('country_code', country).eq('active', true).maybeSingle(),
    admin.from('credit_products').select('id,display_name,credits,sort_order,active').eq('active', true).order('sort_order'),
    admin.from('credit_product_prices').select('product_id,country_code,currency,unit_amount_minor,active').eq('country_code', country).eq('active', true),
  ]);
  const available = Math.max(0, Number(profile?.credits ?? 0) - Number(profile?.credits_reserved ?? 0)); const monthly = Math.max(0, Number(profile?.monthly_credits ?? 0)); const addon = Math.max(0, Number(profile?.addon_credits ?? 0));
  const currency = (region?.currency || productPrices?.[0]?.currency || 'USD').toUpperCase();
  const packs = (products ?? []).map(product => { const price = productPrices?.find(item => item.product_id === product.id && item.currency === currency); return price ? { id: product.id, name: product.display_name, credits: Number(product.credits), unitAmountMinor: Number(price.unit_amount_minor) } : null; }).filter((pack): pack is { id:string; name:string; credits:number; unitAmountMinor:number } => Boolean(pack));
  const firstName = profile?.full_name?.split(' ')[0] || 'creator';
  const quickActions = [
    { href: '/dashboard/media?tool=image', icon: ImagePlus, title: 'Create image', note: '1 / 5 / 10 credits', tone: 'from-blue-500/15 to-violet-500/10' },
    { href: '/dashboard/media?tool=analysis', icon: ScanSearch, title: 'Check authenticity', note: '2 / 5 / 10 credits', tone: 'from-cyan-500/15 to-blue-500/10' },
    { href: '/dashboard/media?tool=video', icon: Video, title: 'Make silent video', note: '10 / 20 credits', tone: 'from-violet-500/15 to-fuchsia-500/10' },
  ] as const;

  return <div className="space-y-6 sm:space-y-7">
    <section className="relative overflow-hidden rounded-[28px] border border-[var(--workspace-border)] bg-[var(--workspace-panel)] p-5 shadow-sm sm:p-7 lg:p-8"><div className="pointer-events-none absolute -right-24 -top-24 size-72 rounded-full bg-[var(--workspace-accent)]/10 blur-3xl"/><div className="relative grid gap-7 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-end"><div><div className="inline-flex items-center gap-2 rounded-full border border-[var(--workspace-border)] bg-[var(--workspace-soft)] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--workspace-muted)]"><Sparkles className="size-3.5 text-[var(--workspace-accent)]"/>Solamentis workspace</div><h1 className="mt-4 max-w-3xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Welcome back, {firstName}.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--workspace-muted)]">Turn an idea into a production asset, inspect an image, or build a silent motion concept without leaving the workspace.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/dashboard/media" className="workspace-primary inline-flex min-h-11 items-center gap-2 rounded-xl px-4 text-sm font-semibold shadow-sm">Open Media Studio <ArrowUpRight className="size-4"/></Link><Link href="/dashboard/projects" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[var(--workspace-border)] bg-[var(--workspace-soft)] px-4 text-sm font-semibold hover:bg-[var(--workspace-hover)]"><FolderKanban className="size-4"/>Browse projects</Link></div></div><div className="rounded-3xl border border-[var(--workspace-border)] bg-[var(--workspace-soft)] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[var(--workspace-muted)]">Wallet</p><p className="mt-1 text-3xl font-bold tracking-tight">{available.toLocaleString()}</p><p className="text-xs text-[var(--workspace-muted)]">credits available</p></div><div className="grid size-12 place-items-center rounded-2xl bg-[var(--workspace-fg)] text-white"><Sparkles className="size-5"/></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-[var(--workspace-border)]"><div className="h-full rounded-full bg-[var(--workspace-accent)]" style={{width:`${Math.min(100,monthly?Math.round((monthly-Math.max(0,monthly-available))/monthly*100):0)}%`}}/></div><div className="mt-3 flex items-center justify-between text-xs text-[var(--workspace-muted)]"><span>{profile?.plan_id || 'free'} plan</span><span>{monthly.toLocaleString()} monthly · {addon.toLocaleString()} purchased</span></div></div></div></section>

    <section className="grid gap-3 md:grid-cols-3">{quickActions.map(({href,icon:Icon,title,note,tone})=><Link key={href} href={href} className={`group rounded-3xl border border-[var(--workspace-border)] bg-gradient-to-br ${tone} p-5 transition hover:-translate-y-0.5 hover:shadow-md`}><div className="flex items-start justify-between gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[var(--workspace-panel)] text-[var(--workspace-fg)] shadow-sm"><Icon className="size-5"/></span><ArrowUpRight className="size-4 text-[var(--workspace-muted)] transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></div><p className="mt-5 text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-[var(--workspace-muted)]">{note}</p></Link>)}</section>

    <CreditWallet monthly={monthly} addon={addon} currency={currency} packs={packs} nextExpiryAt={nextGrant?.expires_at ?? null} nextExpiryCredits={Number(nextGrant?.remaining_amount ?? 0)} />

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[ 'Available credits', available.toLocaleString(), Sparkles, 'Ready to spend now'], ['Projects', String(projects?.length ?? 0), Layers3, 'Active workspace projects'], ['Recent jobs', String(jobs?.length ?? 0), ImagePlus, 'Latest generation activity'], ['Protection', 'Active', ShieldCheck, 'Prompt and image checks']].map(([label,value,Icon,note])=><Card key={String(label)}><CardBody><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium text-[var(--workspace-muted)]">{String(label)}</span><span className="grid size-9 place-items-center rounded-xl bg-[var(--workspace-soft)]"><Icon className="size-4"/></span></div><p className="mt-5 text-2xl font-semibold tracking-tight">{String(value)}</p><p className="mt-1 text-xs text-[var(--workspace-muted)]">{String(note)}</p></CardBody></Card>)}</section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.22fr)_minmax(280px,.78fr)]"><Card><CardBody><div className="flex items-center justify-between gap-4"><div><h2 className="text-sm font-semibold">Recent activity</h2><p className="mt-1 text-xs text-[var(--workspace-muted)]">Your latest generation jobs in this workspace.</p></div><Link href="/dashboard/history" className="text-xs font-semibold text-[var(--workspace-accent)]">View history</Link></div><div className="mt-5"><RecentGenerations jobs={(jobs ?? []) as Array<{ id:string;status:string;prompt:string;quality:string;created_at:string;completed_at:string|null;operation:string;provider:string|null;model:string|null }>} /></div></CardBody></Card><div className="rounded-3xl border border-[var(--workspace-border)] bg-[var(--workspace-fg)] p-6 text-white"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/50">Workspace pulse</p><h2 className="mt-3 text-xl font-semibold capitalize">{profile?.plan_id || 'free'} plan</h2><p className="mt-2 text-sm text-white/60">{profile?.country_name || country} · {available.toLocaleString()} available credits</p><p className="mt-5 text-sm leading-6 text-white/60">Your account, credits, projects and history are synced through the production workspace.</p></div><Link href="/dashboard/settings" className="mt-7 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-white px-4 text-sm font-semibold text-slate-950">Open workspace settings</Link></div></section>

    <section><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[var(--workspace-muted)]">Projects</p><h2 className="mt-1 text-lg font-semibold">Continue a workspace</h2></div><Link href="/dashboard/projects" className="text-xs font-semibold text-[var(--workspace-accent)]">All projects</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{projects?.map(project=><Link key={project.id} href={`/dashboard/projects?project=${project.id}`} className="group rounded-3xl border border-[var(--workspace-border)] bg-[var(--workspace-panel)] p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="aspect-[16/8] rounded-2xl bg-gradient-to-br from-[var(--workspace-soft)] to-[var(--workspace-hover)]"/><div className="mt-4 flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{project.name}</p><p className="mt-1 text-xs text-[var(--workspace-muted)]">{project.width} × {project.height}</p></div><ArrowUpRight className="mt-0.5 size-4 shrink-0 text-[var(--workspace-muted)] transition group-hover:text-[var(--workspace-fg)]"/></div></Link>)}{!projects?.length&&<Link href="/dashboard/media" className="rounded-3xl border border-dashed border-[var(--workspace-border)] bg-[var(--workspace-panel)] p-10 text-center text-sm text-[var(--workspace-muted)] hover:border-[var(--workspace-accent)]">Start your first creation</Link>}</div></section>
  </div>;
}
