import Link from 'next/link';
import { ArrowRight, Clock3, ImagePlus, Layers3, ShieldCheck, Sparkles } from 'lucide-react';
import { getSupabaseServerClient } from '@/server/supabase';
import { getSupabaseAdmin } from '@/server/supabase-admin';

export default async function DashboardPage() {
  const client=await getSupabaseServerClient(); const {data:{user}}=await client.auth.getUser();
  if(!user) return null;
  const admin=getSupabaseAdmin();
  const [{data:profile},{data:projects},{data:jobs}]=await Promise.all([
    admin.from('profiles').select('full_name,plan_id,credits,credits_reserved,country_name').eq('id',user.id).single(),
    admin.from('projects').select('id,name,platform,width,height,updated_at').eq('user_id',user.id).order('updated_at',{ascending:false}).limit(6),
    admin.from('generation_jobs').select('id,status,prompt,quality,created_at,output_path').eq('user_id',user.id).order('created_at',{ascending:false}).limit(6),
  ]);
  const available=Math.max(0,Number(profile?.credits??0)-Number(profile?.credits_reserved??0));
  return <div className="space-y-8"><section><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Overview</p><div className="mt-2 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-semibold tracking-tight">Good to see you, {profile?.full_name?.split(' ')[0]||'creator'}.</h1><p className="mt-2 text-sm text-slate-500">Your creative workspace is connected to Supabase and ready for production workflows.</p></div><Link href="/dashboard/create" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white shadow-sm">New creation <ArrowRight className="size-4" /></Link></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      ['Available credits',String(available),Sparkles,'Usage for your current period'],
      ['Projects',String(projects?.length??0),Layers3,'Active workspace projects'],
      ['Generations',String(jobs?.length??0),ImagePlus,'Recent generation jobs'],
      ['Safety', 'Protected',ShieldCheck,'Prompt and image checks'],
    ].map(([label,value,Icon,note])=><div key={label as string} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm font-medium text-slate-500">{label as string}</span><div className="grid size-9 place-items-center rounded-xl bg-slate-100"><Icon className="size-4" /></div></div><p className="mt-5 text-2xl font-semibold tracking-tight">{value as string}</p><p className="mt-1 text-xs text-slate-400">{note as string}</p></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-semibold">Recent generations</h2><p className="mt-1 text-xs text-slate-400">Latest creative jobs and their state.</p></div><Link href="/dashboard/history" className="text-xs font-semibold text-slate-700">View history</Link></div><div className="divide-y divide-slate-100">{jobs?.length?jobs.map(job=><div key={job.id} className="flex items-center gap-4 px-5 py-4"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100"><Clock3 className="size-4 text-slate-500" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{job.prompt}</p><p className="mt-1 text-xs text-slate-400">{job.quality} · {new Date(job.created_at).toLocaleString()}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${job.status==='succeeded'?'bg-emerald-50 text-emerald-700':job.status==='failed'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{job.status}</span></div>):<div className="p-8 text-sm text-slate-500">No generations yet. Start with a new creation.</div>}</div></div>
      <div className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Workspace status</p><h2 className="mt-3 text-xl font-semibold">{profile?.plan_id||'free'} plan · {profile?.country_name||'Country not set'}</h2><p className="mt-3 text-sm leading-6 text-slate-400">Your profile country, account identity, plan, credits, projects, and usage are synchronized through Supabase.</p><Link href="/dashboard/settings" className="mt-6 inline-flex rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">Manage profile</Link></div></section>
    <section><div className="flex items-center justify-between"><div><h2 className="text-base font-semibold">Projects</h2><p className="mt-1 text-sm text-slate-500">Continue where you left off.</p></div><Link href="/dashboard/projects" className="text-xs font-semibold">All projects</Link></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{projects?.map(p=><Link key={p.id} href={`/dashboard/projects?project=${p.id}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="aspect-[16/9] rounded-xl bg-gradient-to-br from-slate-100 to-slate-200"/><div className="mt-4 flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{p.name}</p><p className="mt-1 text-xs text-slate-400">{p.width} × {p.height}</p></div><ArrowRight className="size-4 text-slate-300 transition group-hover:text-slate-700"/></div></Link>)}{!projects?.length&&<Link href="/dashboard/create" className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">Create your first project →</Link>}</div></section>
  </div>;
}
