'use client';

import type { FormEvent, WheelEvent } from 'react';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Download, ImagePlus, Loader2, Maximize2, Minus, Pencil, Plus, Trash2, WandSparkles, X, XCircle } from 'lucide-react';
import { PLATFORM_SPECS, type PlatformId } from '@/config/platforms';
import { Button } from '@/components/ui/button';
import { Card, CardBody, CardHeader } from '@/components/ui/card';
import { ImageUpload, type UploadedReference } from '@/components/image-upload';

 type JobStatus = 'queued' | 'processing' | 'succeeded' | 'failed' | 'cancelled';
 type Quality = 'preview' | 'standard' | 'premium';
 type Job = { id:string; status:JobStatus; operation:string; prompt:string; size:string; quality:Quality; provider:string|null; model:string|null; output_path?:string|null; error_code:string|null; error_message:string|null; created_at:string; completed_at:string|null; project_id?:string|null; request:Record<string,unknown> };
 type Output = { id?:string; variant:'master'; storage_path:string; mime_type:string; width:number; height:number; byte_size:number; url:string|null };
 type ApiResponse = { job?:Job; output?:Output|null; error?:string };

 const platformLabels:Record<PlatformId,string>={youtube_thumbnail:'YouTube Thumbnail',instagram_post:'Instagram Post',instagram_story:'Instagram Story',facebook_post:'Facebook Post',facebook_cover:'Facebook Cover',pinterest_pin:'Pinterest Pin',linkedin_post:'LinkedIn Post',x_post:'X Post',ad_creative:'Ad Creative',poster:'Poster',website_banner:'Website Banner'};
 const statusCopy:Record<JobStatus,{label:string;detail:string}>={queued:{label:'Queued',detail:'Your request is safely in the generation queue.'},processing:{label:'Generating',detail:'The configured provider is creating your visual.'},succeeded:{label:'Ready',detail:'Your visual passed the pipeline and is ready to use.'},failed:{label:'Failed',detail:'The generation could not be completed.'},cancelled:{label:'Cancelled',detail:'This generation was cancelled.'}};

 export default function CreatePage(){
   const [prompt,setPrompt]=useState(''); const [platform,setPlatform]=useState<PlatformId>('youtube_thumbnail'); const [quality,setQuality]=useState<Quality>('standard'); const [loading,setLoading]=useState(false); const [loadingHistory,setLoadingHistory]=useState(false); const [message,setMessage]=useState(''); const [jobId,setJobId]=useState<string|null>(null); const [historyId,setHistoryId]=useState<string|null>(null); const [job,setJob]=useState<Job|null>(null); const [output,setOutput]=useState<Output|null>(null); const [projectName,setProjectName]=useState<string|null>(null); const [modalOpen,setModalOpen]=useState(false); const [zoom,setZoom]=useState(1); const [editPrompt,setEditPrompt]=useState(''); const [editing,setEditing]=useState(false); const [downloading,setDownloading]=useState(false); const [reference,setReference]=useState<UploadedReference|null>(null); const pollTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
   const spec=PLATFORM_SPECS[platform]; const isActive=job?.status==='queued'||job?.status==='processing'; const status=job?statusCopy[job.status]:null; const imageUrl=output?.url??null;

   async function loadJob(id:string){try{const response=await fetch(`/api/generate/${id}`,{cache:'no-store'});const data=await response.json() as ApiResponse;if(!response.ok||!data.job)throw new Error(data.error||'Unable to read generation status.');setJob(data.job);setOutput(data.output??null);return data.job.status;}catch(error){setMessage(error instanceof Error?error.message:'Unable to read generation status.');return null;}}
   async function loadHistory(id:string){setLoadingHistory(true);setMessage('');try{const response=await fetch(`/api/history/${id}`,{cache:'no-store'});const data=await response.json() as ApiResponse & {project?:{name:string}|null};if(!response.ok||!data.job)throw new Error(data.error||'Unable to open saved generation.');const request=data.job.request??{};const savedPlatform=typeof request.platform==='string'&&request.platform in PLATFORM_SPECS?request.platform as PlatformId:undefined;setHistoryId(id);setJobId(id);setJob(data.job);setPrompt(data.job.prompt);setEditPrompt('');setQuality(data.job.quality);if(savedPlatform)setPlatform(savedPlatform);setOutput(data.output??null);setProjectName(data.project?.name??null);}catch(error){setMessage(error instanceof Error?error.message:'Unable to open saved generation.');}finally{setLoadingHistory(false);}}
   useEffect(()=>{const id=new URLSearchParams(window.location.search).get('history');if(id)void loadHistory(id);},[]);
   useEffect(()=>{if(!jobId||job?.status==='succeeded'||job?.status==='failed'||job?.status==='cancelled')return;let cancelled=false;const poll=async()=>{const current=await loadJob(jobId);if(!cancelled&&current&&['queued','processing'].includes(current))pollTimer.current=setTimeout(poll,1800);};void poll();return()=>{cancelled=true;if(pollTimer.current)clearTimeout(pollTimer.current);};},[jobId,job?.status]);
   useEffect(()=>()=>{if(pollTimer.current)clearTimeout(pollTimer.current);if(reference?.previewUrl)URL.revokeObjectURL(reference.previewUrl);},[reference?.previewUrl]);
   useEffect(()=>{if(!modalOpen)return;const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape')setModalOpen(false);if(event.key==='+'||event.key==='=')setZoom(v=>Math.min(3,Number((v+.1).toFixed(2))));if(event.key==='-')setZoom(v=>Math.max(.5,Number((v-.1).toFixed(2))));if(event.key==='0')setZoom(1);};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[modalOpen]);
   function onZoomWheel(event:WheelEvent<HTMLDivElement>){if(!event.ctrlKey&&!event.metaKey)return;event.preventDefault();setZoom(v=>Math.min(3,Math.max(.5,Number((v+(event.deltaY<0?.1:-.1)).toFixed(2)))));}
   function openPreview(){if(!imageUrl)return;setZoom(1);setModalOpen(true);}
   async function submit(event:FormEvent){event.preventDefault();setLoading(true);setMessage('');setJob(null);setJobId(null);setHistoryId(null);setOutput(null);setProjectName(null);try{const response=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({operation:'generateImage',prompt:prompt.trim(),platform,quality,size:`${spec.width}x${spec.height}`,width:spec.width,height:spec.height,referenceImageStoragePaths:reference?.path?[reference.path]:[]})});const data=await response.json() as {jobId?:string;error?:string};if(!response.ok||!data.jobId)throw new Error(data.error||'Generation could not be started.');setJobId(data.jobId);setMessage('Generation started.');await loadJob(data.jobId);}catch(error){setMessage(error instanceof Error?error.message:'Request failed');}finally{setLoading(false);}}
   async function applyEdit(event:FormEvent){event.preventDefault();if(!historyId||!editPrompt.trim()||editing)return;setEditing(true);setMessage('');try{const response=await fetch(`/api/history/${historyId}/edit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:editPrompt.trim(),quality})});const data=await response.json() as {jobId?:string;error?:string};if(!response.ok||!data.jobId)throw new Error(data.error||'Unable to create edit job.');setJobId(data.jobId);setHistoryId(data.jobId);setJob(null);setOutput(null);setMessage('Edit started.');setEditPrompt('');window.history.replaceState({},'',`/dashboard/create?history=${data.jobId}`);await loadJob(data.jobId);}catch(error){setMessage(error instanceof Error?error.message:'Edit request failed');}finally{setEditing(false);}}
   async function downloadCurrent(){if(!historyId&&!jobId)return;const id=historyId??jobId;setDownloading(true);try{const response=await fetch(`/api/history/${id}/download`,{cache:'no-store'});if(!response.ok){const data=await response.json().catch(()=>({})) as {error?:string};throw new Error(data.error||'Download failed.');}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`solamentis-${id}.webp`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);}catch(error){setMessage(error instanceof Error?error.message:'Download failed.');}finally{setDownloading(false);}}
   async function deleteCurrent(){if(!historyId)return;if(!window.confirm('Permanently delete this generation, its saved image, and history? This cannot be undone.'))return;const response=await fetch(`/api/history/${historyId}`,{method:'DELETE'});const data=await response.json() as {error?:string};if(!response.ok){setMessage(data.error||'Unable to delete generation.');return;}window.location.href='/dashboard/history';}

   return <div className="space-y-7 sm:space-y-8">
     <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Studio</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">Turn an idea into a finished visual.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Prompt, add a reference image when useful, generate, review, edit, and download from one responsive workspace.</p></div>{historyId&&<a href="/dashboard/history" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 hover:bg-slate-50"><ArrowLeft className="size-4"/> History</a>}</div>
     {loadingHistory&&<div className="flex items-center gap-2 rounded-2xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-700"><Loader2 className="size-4 animate-spin"/> Restoring your saved studio state…</div>}
     <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(360px,520px)]">
       <Card><CardHeader><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-slate-950 text-white"><WandSparkles className="size-5"/></span><div><p className="text-sm font-semibold">{historyId?'Saved generation':'New generation'}</p><p className="text-xs text-slate-400">The provider and model remain configuration-driven.</p></div></div></CardHeader><CardBody><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Platform<select value={platform} onChange={e=>setPlatform(e.target.value as PlatformId)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 px-3.5 py-3 outline-none focus:border-slate-400 focus:ring-4 focus:ring-slate-100">{Object.keys(PLATFORM_SPECS).map(id=><option key={id} value={id}>{platformLabels[id as PlatformId]}</option>)}</select></label><label className="block text-sm font-medium">Quality<select value={quality} onChange={e=>setQuality(e.target.value as Quality)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 px-3.5 py-3 outline-none focus:border-slate-400 focus:ring-4 focus:ring-slate-100"><option value="preview">Preview · 1 credit</option><option value="standard">Standard · 2–3 credits</option><option value="premium">Premium · 4–5 credits</option></select></label></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">Canvas</p><p className="mt-1 text-sm font-semibold">{spec.width} × {spec.height}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">Max export</p><p className="mt-1 text-sm font-semibold">{(spec.maxBytes/1000000).toFixed(1)} MB</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">Reference</p><p className="mt-1 text-sm font-semibold">{reference?'Attached':'Optional'}</p></div></div><ImageUpload current={reference} onChange={setReference}/><label className="block text-sm font-medium">Creative brief<textarea required minLength={3} rows={11} value={prompt} onChange={e=>setPrompt(e.target.value)} className="mt-2 min-h-48 w-full resize-y rounded-2xl border border-slate-200 px-4 py-3.5 leading-6 outline-none focus:border-slate-400 focus:ring-4 focus:ring-slate-100" placeholder="Describe the subject, composition, lighting, style, text hierarchy, brand feel, and constraints. Mention how the uploaded reference should influence the result."/></label>{message&&<div role="status" className={`rounded-xl p-3 text-sm ${job?.status==='failed'?'bg-red-50 text-red-700':'bg-slate-100 text-slate-600'}`}>{message}</div>}{!historyId&&<Button type="submit" disabled={loading||prompt.trim().length<3||isActive} loading={loading} className="w-full">{loading?'Starting generation…':isActive?'Generation in progress…':'Generate visual'}{!loading&&!isActive&&<ArrowRight className="size-4"/>}</Button>}</form></CardBody></Card>
       <aside className="space-y-4"><Card><CardHeader><div className="flex items-center justify-between gap-4"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Canvas</p><h2 className="mt-1 truncate text-sm font-semibold">{projectName||'Generated visual'}</h2></div>{job&&<span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${job.status==='succeeded'?'bg-emerald-50 text-emerald-700':job.status==='failed'||job.status==='cancelled'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{status?.label}</span>}</div></CardHeader><CardBody className="p-0">{imageUrl?<><div className="overflow-hidden bg-slate-950"><button type="button" onClick={openPreview} className="block w-full focus:outline-none focus:ring-4 focus:ring-blue-100" aria-label="Open image preview"><img src={imageUrl} alt="Generated visual" className="mx-auto block max-h-[620px] w-full object-contain"/></button></div><div className="flex flex-wrap gap-2 border-t border-slate-100 p-4"><Button type="button" variant="secondary" onClick={openPreview}><Maximize2 className="size-4"/>Preview</Button><Button type="button" onClick={()=>void downloadCurrent()} disabled={downloading}>{downloading?<Loader2 className="size-4 animate-spin"/>:<Download className="size-4"/>}Download</Button>{historyId&&<Button type="button" variant="danger" onClick={()=>void deleteCurrent()}><Trash2 className="size-4"/>Delete</Button>}</div></>:<div className="p-4"><div className="grid min-h-[360px] place-items-center rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center sm:min-h-[420px]">{job?<div>{job.status==='failed'||job.status==='cancelled'?<XCircle className="mx-auto size-9 text-red-300"/>:job.status==='succeeded'?<ImagePlus className="mx-auto size-9 text-slate-400"/>:<Loader2 className="mx-auto size-9 animate-spin text-blue-500"/>}<p className="mt-4 text-sm font-semibold text-slate-700">{status?.label}</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-500">{status?.detail}</p>{job.error_message&&<p className="mt-3 max-w-sm rounded-lg bg-red-50 px-3 py-2 text-xs leading-5 text-red-700">{job.error_message}</p>}{isActive&&<p className="mt-4 inline-flex items-center gap-2 text-[11px] text-slate-400"><Clock3 className="size-3.5"/>Checking automatically…</p>}</div>:<div><ImagePlus className="mx-auto size-9 text-slate-300"/><p className="mt-4 text-sm font-semibold text-slate-600">Your generated visual appears here</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-400">Upload a reference when needed, then describe what you want to create.</p></div>}</div></div>}</CardBody></Card>
         {historyId&&job?.status==='succeeded'&&<Card><CardBody><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-blue-50 text-blue-600"><Pencil className="size-4"/></span><div><p className="text-sm font-semibold">Edit this saved image</p><p className="text-xs text-slate-400">The original stays preserved; an edit creates a new generation.</p></div></div><form onSubmit={applyEdit} className="mt-4"><textarea required minLength={3} rows={4} value={editPrompt} onChange={e=>setEditPrompt(e.target.value)} className="w-full resize-y rounded-2xl border border-slate-200 px-4 py-3 text-sm leading-6 outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-50" placeholder="Describe exactly what should change in the image…"/><Button type="submit" disabled={editing||!editPrompt.trim()} loading={editing} className="mt-3 w-full">{editing?'Applying edit…':'Apply edit'}<WandSparkles className="size-4"/></Button></form></CardBody></Card>}
         {job&&<div className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Generation details</p><p className="mt-2 text-sm text-slate-200">{job.operation}</p></div>{job.status==='succeeded'&&<CheckCircle2 className="size-5 text-emerald-400"/>}</div><div className="mt-5 grid grid-cols-2 gap-3 text-[11px]"><div className="rounded-xl bg-white/5 p-3"><span className="text-slate-500">Canvas</span><p className="mt-1 text-slate-200">{String(job.request?.width??spec.width)} × {String(job.request?.height??spec.height)}</p></div><div className="rounded-xl bg-white/5 p-3"><span className="text-slate-500">Quality</span><p className="mt-1 capitalize text-slate-200">{job.quality}</p></div><div className="rounded-xl bg-white/5 p-3"><span className="text-slate-500">Provider</span><p className="mt-1 truncate text-slate-200">{job.provider||'configured route'}</p></div><div className="rounded-xl bg-white/5 p-3"><span className="text-slate-500">Model</span><p className="mt-1 truncate text-slate-200">{job.model||'configured model'}</p></div></div></div>}
       </aside>
     </div>
     {modalOpen&&imageUrl&&<div className="fixed inset-0 z-[100] bg-slate-950/95 p-3 sm:p-6" onWheel={onZoomWheel}><div className="flex h-full flex-col overflow-hidden rounded-3xl border border-white/10 bg-slate-900"><div className="flex shrink-0 items-center justify-between gap-3 border-b border-white/10 px-4 py-3 text-white"><div><p className="text-sm font-semibold">Image preview</p><p className="text-[11px] text-slate-400">Ctrl/Cmd + wheel or +/− to zoom · Esc to close</p></div><div className="flex items-center gap-1"><button type="button" onClick={()=>setZoom(v=>Math.max(.5,Number((v-.1).toFixed(2))))} aria-label="Zoom out" className="rounded-lg p-2 hover:bg-white/10"><Minus className="size-4"/></button><span className="min-w-12 text-center text-xs font-semibold">{Math.round(zoom*100)}%</span><button type="button" onClick={()=>setZoom(v=>Math.min(3,Number((v+.1).toFixed(2))))} aria-label="Zoom in" className="rounded-lg p-2 hover:bg-white/10"><Plus className="size-4"/></button><button type="button" onClick={()=>setZoom(1)} className="rounded-lg px-2 py-2 text-[11px] font-semibold hover:bg-white/10">Reset</button><button type="button" onClick={()=>setModalOpen(false)} aria-label="Close preview" className="rounded-lg p-2 hover:bg-white/10"><X className="size-4"/></button></div></div><div className="min-h-0 flex-1 overflow-auto p-4 sm:p-8"><div className="flex min-h-full min-w-max items-center justify-center"><img src={imageUrl} alt="Full generated visual" draggable={false} className="origin-center max-w-none rounded-xl shadow-2xl" style={{width:`${zoom*100}%`,maxWidth:'none'}}/></div></div></div></div>}
   </div>;
 }
